version: "3.9"
services: 
  postgres:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_USER=rishav
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=hide1337
      - POSTGRES_DB=simple_bank_new

  api: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://rishav:hide1337@postgres:5432/simple_bank_new?sslmode=disable
    depends_on:
      - postgres 
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
